version: "3"

services:

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/habitdb

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: habitdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
